[WIP] Add LOOCV example
chemo-wakate/tutorial-7th pull request #1
Opened 2017-10-28 00:58 UTC by yamasakih

2017-10-28 01:16 UTC, yamasakih commented
@hkaneko1985 @kubor 
現在のscikit-learnのバージョンは0.18でLOOCVやk-fold CVのためのモジュールはcross_validationですが0.2からmodel_selectionに変わるようなので、こちらを使おうと思います。いかがでしょうか？

2017-10-28 05:34 UTC, kubor commented
良いと思います。

2017-10-28 06:32 UTC, yamasakih commented
KFoldでも引数次第でランダムにトレーニングセットとテストセットに分割できるので
ShuffleSpliteの存在意義がよくわからない 😅

2017-10-28 06:34 UTC, hkaneko1985 commented
賛成です。

2017-10-28 06:57 UTC, yamasakih commented
ご賛同ありがとうございました。

2017-10-28 09:26 UTC, hkaneko1985 commented
山﨑さんありがとうございます。git cloneしようとしましたが失敗しました。私はまだアクセス権限がない状態でしょうか？

$ git clone https://github.com/chemo-wakate/tutorial-7th.git
fatal: could not create work tree dir 'tutorial-7th': Permission denied

2017-10-28 09:35 UTC, hkaneko1985 commented
LOOCVやk-fold CVの例の意図としては、クラス分類のクロスバリデーションを参考にして、受講者の皆さんは回帰分析でのクロスバリデーションを考えてみよう！ということでしょうか？

2017-10-28 09:52 UTC, yamasakih commented
@hkaneko1985

ご意見ありがとうございます。

まさにこちらからも聞きたかったことでして、
今回は試行錯誤するというコンセプトなので
自分でまずCVする方法を探してもらって、
どうしても見つからない、見つけたけどわからない
という方にヒントとして後出しで見せるのが
いいかなと思ってます。

あと単純にファシリテーターがやり方知らないのは
困るので参考にしてもらおうと思い作ってます。

いかかでしょうな？

2017-10-28 10:19 UTC, yamasakih commented
@kubor san 金子さんがクローンできない原因なんだと思いますか？

2017-10-28 21:14 UTC, hkaneko1985 commented
CVについて了解です！私も後出しがよいと思います。それまでは受講者の皆さんに試行錯誤していただきましょう！

クローンについてもありがとうございます。原因は分かりませんが、ディレクトリをかえたらクローンできました。最初のディレクトリもスペースがないものだったのですが。。。とりあえずクローンできたので良かったです。dockerファイルをダウンロードしています。

2017-10-28 21:30 UTC, hkaneko1985 commented
すみません、docker関係なかったですね。ブランチをクローンするのにbオプションが必要なことを知り、なんどかcloneできました。

2017-10-28 21:33 UTC, hkaneko1985 commented
Cross-validation.ipynb をローカルで確認できるところまできました。すみません、お騒がせしました。

2017-10-28 22:18 UTC, yamasakih commented
ああ、すいません。お伝えしてなかったですね。

`git fetch` した後に

`git checkout feature/Add-LOOCV`

する必要ありましたね。

今作成中なので、完成したらまたお伝えするのでレビューお願いします。

あとこちら

```
まさにこちらからも聞きたかったことでして、
今回は試行錯誤するというコンセプトなので
自分でまずCVする方法を探してもらって、
どうしても見つからない、見つけたけどわからない
という方にヒントとして後出しで見せるのが
いいかなと思ってます。
```

ご意見くださると助かります。

2017-10-28 22:19 UTC, hkaneko1985 commented
すみません、途中だったんですね。レビューしちゃいました・・・。

2017-10-28 22:20 UTC, hkaneko1985 commented
私も後出しがよいと思います。それまでは受講者の皆さんに試行錯誤していただきましょう！

2017-10-28 22:23 UTC, hkaneko1985 commented
わたしはもっぱらGridSearchCVやcross_val_predictで済ませてしまうので勉強になりました。

2017-10-28 22:57 UTC, yamasakih commented
@hkaneko1985 san
すいません。タイトルに [WIP] ってついているときは作業中です。
[WIP] でもレビューが必要なときはこちらからお伝えしますね 🙏 

WIPに関してまで一緒に勉強してなかったですね 💯 

レビューありがとうございます。
こちらでも確認させてもらいますね。

>私も後出しがよいと思います。それまでは受講者の皆さんに試行錯誤していただきましょう！
ご賛同ありがとうございます！

>わたしはもっぱらGridSearchCVやcross_val_predictで済ませてしまうので勉強になりました。
cross_val_predict勉強してみます！

2017-10-29 01:42 UTC, yamasakih commented
@hkaneko1985 san
GridSearchCVってSVM以外でも使えるんですか？
特定のパラメータをずっと変化できるんでしたっけ。
ついでにTrainingとTestもわけれるのでしょうか？

maskot sanも使ってたような気がしますね。

2017-10-29 21:18 UTC, hkaneko1985 commented
解説ありがとうございます。WIPについて了解しました。Work In Progressですね。

GridSearchCVは確かSVM, SVRだけだったと思います。
他は、パラメータをふってcross_val_predictでCV予測値出して、そのr2が高いパラメータの値を選択、のようにしています。
GridSearchCVはクロスバリデーションだけで、training と test にはわけられなかったと思います。なので、最初に training と test にわけて、training で GridSearchCV という感じです。

2017-10-29 21:50 UTC, yamasakih commented
金子さん解説ありがとうございます。

>解説ありがとうございます。WIPについて了解しました。Work In Progressですね。

はい。おっしゃるとおりWork in Progressです。
GithubにおけるWIP作業の仕方はこちらをご覧ください。
[Work in ProgressパターンによるPull Requestを利用した開発フロー](https://qiita.com/numa08/items/b676e38e3dbabfd39d18)

>GridSearchCVは確かSVM, SVRだけだったと思います。
>他は、パラメータをふってcross_val_predictでCV予測値出して、そのr2が高いパラメータの値を選択、のようにしています。

SVMのSVC(SVMによるクラス分類)でもできること確認しました。
一例として乗せることにします。あくまでSVMのGridSearchを補助する機能のようですね。

>GridSearchCVはクロスバリデーションだけで、training と test にはわけられなかったと思います。なので、最初に training と test にわけて、training で GridSearchCV という感じです。

引数cvにKFoldやLeaveOneOutなどのクラスを与えることでそれでCVしてもらえるようですよ。
詳しくはまとめておきますね。

2017-10-29 22:09 UTC, hkaneko1985 commented
作業の仕方について了解です。

> 引数cvにKFoldやLeaveOneOutなどのクラスを与えることでそれでCVしてもらえるようですよ。
はい、わたしもそのようにしてクロスバリデーションしています。だいたい cv = 5 か cv = 2 ですね。

人によって、training set, validation set, test set の意味合いが違うので、最初に定義したほうがよいかもしれませんね。

2017-10-29 22:32 UTC, yamasakih commented
@hkaneko1985 san

定義いいですね。まず我々でコンセンサスとりますかね。

私は
- training set: モデルを構築するのに使うデータ
- test set: Training setで構築したモデルの性能評価をし、どのモデルが良いかを決定するのに使うデータ
- validation set: training set, test setで作成、決定したモデルの外部データへの性能評価をするためのデータ。external setとも呼ばれる。

と認識しています。金子さんはいかがでしょうか？

2017-10-29 23:44 UTC, yamasakih commented
estimator interfaceを実装しているものならなんでもGridSearchCVが使えるようです。

[sklearn.model_selection.GridSearchCV](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV)

2017-10-30 00:05 UTC, yamasakih commented
GridSearchCVの結果を表示するのも
`grid_scores_`フィールドでは古く`cv_results_`フィールドを用いることが推奨されているようです。

2017-10-30 00:21 UTC, yamasakih commented
@hkaneko1985 @kubor 

作成しました。レビューお願いします！:pray:

実行はできないもののJupyterのコードのみを確認するために
Gistと呼ばれるサイトにアップロードしたもののリンクもお伝えしておきます。
[Cross-validation.ipynb](https://gist.github.com/yamasakih/5226f65a7ba91e2338a6d904ab4bf5ba)

2017-10-30 01:59 UTC, hkaneko1985 commented
山﨑さん、いろいろな情報ありがとうございます！

私は、山﨑さんの test set と validation set を逆に使っています。
・training set：モデルを構築するためのデータ
・validation set：ハイパーパラメータを決めるためのデータ
・test set：yをblind にして、training set・validationセットで作られたモデルの性能を最終的に確認するためのデータ
他の人はどうなんだろうと思って調べてみましたら、wikipediaがありました。
https://en.wikipedia.org/wiki/Training,_test,_and_validation_sets

GridSearchCV、なんと！便利になってますねー！

作成もありがとうございます、謹んでレビュー致します！

2017-10-30 02:04 UTC, yamasakih commented
@hkaneko1985 san

>他の人はどうなんだろうと思って調べてみましたら、wikipediaがありました。
>https://en.wikipedia.org/wiki/Training,_test,_and_validation_sets

参考文献ありがとうございました。確認してみますね。

ちなみにGithubにおけるレビューは本当に見るだけで結構です。
修正してcommitするのはこちらでしまする 👍 
そうじゃないとこちらの変更とそちらの変更がぶつかることがあるので
どうしても自分で変更したほうが話が早いなどという時は新しくブランチ作ってもらうと助かります 🙏

2017-10-30 02:06 UTC, yamasakih commented
Wikipedia見る感じでは金子さんと同じ意見のようですね 🤔 

では金子スタイルに合わせましょう！

```
・training set：モデルを構築するためのデータ
・validation set：ハイパーパラメータを決めるためのデータ
・test set：yをblind にして、training set・validationセットで作られたモデルの性能を最終的に確認するためのデータ
```

こちらと定義致します！ 🎉

2017-10-30 02:09 UTC, hkaneko1985 commented
レビューの仕方についてありがとうございます、了解しました。

データのスタイルについても了解です。合わせていただきありがとうございます！

2017-10-30 02:10 UTC, yamasakih commented
>データのスタイルについても了解です。合わせていただきありがとうございます！

金子さんの講義資料の最初の方に定義として入れるとよさそうですね。いかがでしょうか？

2017-10-30 02:11 UTC, hkaneko1985 commented
> 金子さんの講義資料の最初の方に定義として入れるとよさそうですね。いかがでしょうか？

おっしゃる通りですね、入れます！

2017-10-30 04:10 UTC, kubor requested changes
ありがとうございます！
すごく良いストーリーになっていてわかりやすいと思います。

いくつか修正・加筆したほうが良さそうなところにコメントをいれました。
ご確認ください。

2017-10-30 04:10 UTC, kubor commented on advanced/Cross-validation.ipynb
> +    "ランダムに分割したい場合はrandom_state=None, shuffle=Trueとする。"
ランダムにと言うより、再現性を担保せずにという意味合いのほうが伝わるかもしれません。
`random_state=123` などとして、intを指定するとseed値を固定することも可能であることを伝えられるとより参考になりそうです。

2017-10-30 04:10 UTC, kubor commented on advanced/Cross-validation.ipynb
> +    "乱数を固定したくない場合はrandom_state=Noneとする。このルールは他の関数でも適用される。"
Kfoldと言い回しを統一したいです

2017-10-30 04:10 UTC, kubor commented on advanced/Cross-validation.ipynb
> +   ]
import順序をアルファベットソートしました。

```
import numpy as np
import pandas as pd
import sys

from sklearn import svm
from sklearn.datasets import load_iris, load_digits
from sklearn.model_selection import KFold, ShuffleSplit, GroupKFold, \
                                                                StratifiedKFold, StratifiedShuffleSplit,  \
                                                                LeaveOneOut, LeavePOut, \
                                                                cross_val_predict, cross_val_score, GridSearchCV


print(sys.version_info)
```

2017-10-30 04:10 UTC, kubor commented on advanced/Cross-validation.ipynb
> +    "ランダムに分割したい場合はrandom_state=None, shuffle=Trueとする。"
ランダムに分割したい場合は `shuffle=True` とし、seed値を固定しない場合は `random_state=None` とする。

ぐらい丁寧に書いてあげたほうが良いかもです。

2017-10-30 04:10 UTC, kubor commented on advanced/Cross-validation.ipynb
> +    "X_iris"
長いですし、 `X_iris.head()` でどうでしょう。
サイズが分かっていないとあんまり生で出さない方が身のためですし（ブラウザ爆発する）。

そして直後のセルで `X_iris.shape` を使ってデータサイズを確認するのもよくやるので追加しても良いかもしれません。

2017-10-30 04:10 UTC, kubor commented on advanced/Cross-validation.ipynb
> +    "これらの一連の工程は4に参照するcross_val_predictやcross_val_scoreを用いることで簡単に行うことができる。"
ここまでのめんどくささがスキップできるとこの一文ではっきりわかってすごくテンションが上りました

2017-10-30 04:10 UTC, kubor commented on advanced/Cross-validation.ipynb
> +    "print('Best Estimator:\\n%s\\n' % clf.best_estimator_)\n",
%フォーマットはちょっと古いので `str.format()` か f-strings で書きたいところです。

個人的には `str.format()` が慣れてしまったのですが、 f-strings も良さそうですね。
http://postd.cc/new-string-formatting-in-python/

2017-10-30 04:10 UTC, kubor commented on advanced/Cross-validation.ipynb
> +    "したがって新たに学ぶなら1〜4章で説明したモジュールの関数やクラスを学んだ方が良い。"
しびれました。

2017-10-30 04:12 UTC, yamasakih commented on advanced/Cross-validation.ipynb
> +   ]
Jupyterで出てきた順に並べていますがこちらがよさそうならこちらに変えますね 👍

2017-10-30 04:14 UTC, yamasakih commented on advanced/Cross-validation.ipynb
> +    "乱数を固定したくない場合はrandom_state=Noneとする。このルールは他の関数でも適用される。"
@kubor @hkaneko1985 
K-foldで出てきたグループのことfoldと指しているのですが
あまり適切でないですかね？
みなさんはなんていいますかね？

2017-10-30 04:15 UTC, yamasakih commented on advanced/Cross-validation.ipynb
> +    "これらの一連の工程は4に参照するcross_val_predictやcross_val_scoreを用いることで簡単に行うことができる。"
テンション上がってきた (^o^≡^o^)

2017-10-30 04:16 UTC, yamasakih commented on advanced/Cross-validation.ipynb
> +    "したがって新たに学ぶなら1〜4章で説明したモジュールの関数やクラスを学んだ方が良い。"
![image](https://user-images.githubusercontent.com/10294378/32154509-8cbc60cc-bd74-11e7-8c67-0b3308a585d8.png)

2017-10-30 04:18 UTC, kubor commented on advanced/Cross-validation.ipynb
> +    "乱数を固定したくない場合はrandom_state=Noneとする。このルールは他の関数でも適用される。"
すいません、ここで言いたかったのは seed固定して再現性担保するかどうかという説明の言い回しについてです。

2017-10-30 04:20 UTC, yamasakih commented on advanced/Cross-validation.ipynb
> +    "乱数を固定したくない場合はrandom_state=Noneとする。このルールは他の関数でも適用される。"
ああ、KFoldクラスの説明をした時と同じ「再現性を担保せずに」という
言い回しにしたいということですね。
ありがとうございます 👍

2017-10-30 04:24 UTC, yamasakih commented on advanced/Cross-validation.ipynb
> +   ]
ちゃんと2行あけてpep8に怒られないようにしているpythonistaの鑑。
done.

2017-10-30 04:30 UTC, yamasakih commented
Kubor san のレビューで変更するついでに
Training, Validation, Test setも金子スタイルに変更します。

2017-10-30 04:32 UTC, yamasakih commented
金子スタイルでいうvalidation setが
scikit-learnのドキュメントではtest setとなっているのがいささか混乱を呼びそうなので
`scikit-learnなどではtest setとなっているが今回はvalidation setと呼ぶ`
と最初にしっかり言ったほうがいいかもですね。

2017-10-30 04:37 UTC, yamasakih commented on advanced/Cross-validation.ipynb
> +    "ランダムに分割したい場合はrandom_state=None, shuffle=Trueとする。"
いいアイディアですね。done.

2017-10-30 04:38 UTC, yamasakih commented on advanced/Cross-validation.ipynb
> +    "乱数を固定したくない場合はrandom_state=Noneとする。このルールは他の関数でも適用される。"
done.

2017-10-30 04:41 UTC, yamasakih commented on advanced/Cross-validation.ipynb
> +    "ランダムに分割したい場合はrandom_state=None, shuffle=Trueとする。"
他のと統一するためにランダムではなく「再現性を担保せずに」に変更しつつ
説明を追加しました。
done.

2017-10-30 04:43 UTC, kubor commented
ごにょごにょメモとか書いたり、セル追加したipynbにそのまま最新コミットが追加されたmasterをgit pull出来ないのをどうにかしたい。
少なくとも今回は最初にアナウンスしておきますか。ポイントとしては以下。

- git管理下（特にそのままmaster）でノートを編集するとリモートリポジトリで変更があった場合にpullできない（ `stash` したり `checkout -b`する必要がある）

なにかおすすめの運用方法無いですか＞＜

@yamasakih @hkaneko1985

2017-10-30 04:44 UTC, yamasakih commented on advanced/Cross-validation.ipynb
> +    "X_iris"
X_iris.shape知らなかったです。ありがとうございました。

いつもは`len(X_iris.index)`を使っていましたがこちらのほうが楽ですね。
採用致します。 

done.

2017-10-30 04:49 UTC, yamasakih commented on advanced/Cross-validation.ipynb
> +    "print('Best Estimator:\\n%s\\n' % clf.best_estimator_)\n",
%古いんですね。ご指摘ありがとうございます。

f-strings使ってみました。超便利ーーー！ 💯 

done.

2017-10-30 04:52 UTC, yamasakih commented
@kubor san

確かに受講者がせっせとメモとったり作ったNotebookがどっかにパァーンするのは悲しいですね 💣 
stashなどに慣れてない方には原始的ですが
バックアップとして別フォルダに保存してって言ったほうが良いかもですね。

2017-10-30 04:56 UTC, yamasakih commented
@kubor san 
レビューいただいた内容修正しました。ご確認下さい。
https://gist.github.com/yamasakih/5226f65a7ba91e2338a6d904ab4bf5ba

2017-10-30 05:51 UTC, kubor approved these changes
良いと思います！

2017-10-30 06:05 UTC, yamasakih commented
@kubor san ありがとうございました！ 🍵 
@hkaneko1985 san のレビューを待って特に問題なければマージしまする。

2017-10-30 09:46 UTC, hkaneko1985 commented
遅くなりすみません、レビューしました。
基本的な話から徐々に積み上げて丁寧に説明されていて分かりやすい資料と感じました。
一点、資料を読んだ受講者の中には、「結局、どれでクロスバリデーションすればいいの？」ってなる方もいらっしゃるかと思います。当日の山﨑さんの補足説明があればOKな話ですので、この資料で全く問題ないと思いますが、たとえば、クロスバリデーションのゴールとして、「4. Cross validtionおよびモデル作成をし予測まで一括で行う関数」 から説明して、"この関数を押さえておけばとりあえずクロスバリデーションできるよ、中でどんなことやってるのかというと・・・"、といったやり方も一案かと思いました。

2017-10-30 10:17 UTC, yamasakih commented
@hkanejo1985 san
レビューありがとうございました。
おっしゃるとおりですね。Jupyterドキュメント中にもその旨を追記してみます！

2017-10-30 13:07 UTC, yamasakih commented
@hkaneko1985 san
レビューを参考に作り直しました。

以下のことをしました。

- 最初に概要として4の`cross_val_score`たちを使えばよいという解説
- cv=10などで10-fold cross validationを行える説明を4.2あたりに追加しました。

gistはこちらになります。
[Cross-validation.ipynb](https://gist.github.com/yamasakih/5226f65a7ba91e2338a6d904ab4bf5ba)

こちらで問題なかったら完成だと思いますのでマージしておいてください。
よろしくお願いします :pray:

2017-10-30 20:58 UTC, hkaneko1985 commented
山﨑さんご対応いただきありがとうございます。
拝見致しました。
受講者が迷う心配も皆無かと思います。
マージ致します。

2017-10-30 21:03 UTC, hkaneko1985 approved these changes

2017-10-30 21:04 UTC, merged

2017-10-30 21:22 UTC, yamasakih commented
金子さん、マージありがとうございました！