Add DecisionTree Example Jupyter Note
chemo-wakate/tutorial-7th pull request #2
Opened 2017-10-30 02:41 UTC by yamasakih

Decision Treeの使い方を説明するJupyter Noteを作成します。

2017-10-30 02:43 UTC, yamasakih commented
@hkaneko1985 san

DecisionTreeRegressionやDecisionTreeClassifierに乱数を設定する引数あるけど
アルゴリズムのどこかで乱数使っていましたっけ？

それともアルゴリズムでは使ってなくてCVのデータを取ってくるところで使っているのかな？ 🤔

2017-10-30 02:50 UTC, hkaneko1985 commented
こちらもありがとうございます。確認しました。
splitter 引数を"random"にしたとき用で、ノードの閾値をランダムに決めるときに乱数を使うのではないでしょうか。それ以外では決定木にランダム性はないと思います。

2017-10-30 02:51 UTC, yamasakih commented
やはりそうですかね！
ありがとうございました！

2017-10-30 05:58 UTC, yamasakih commented
@kubor san

決定木の図を書こうと思ったら`graphviz`というソフトが必要なのですがどうしましょうか？

http://scikit-learn.org/stable/modules/tree.html#tree

macとかなら`brew install graphviz`で入るのですがubuntsuだといささか面倒ですかね？

いかがでしょうか？

2017-10-30 08:25 UTC, yamasakih commented
@kubor @hkaneko1985 
決定木の使い方をまとめたドキュメントできました。
ご確認下さい。

gistにまとめたものはこちらになります。
[DesicionTree.ipynb](https://gist.github.com/yamasakih/1b661ae29b32240afdfb0f709b9e0a03)

2017-10-31 21:01 UTC, hkaneko1985 commented
山﨑さん決定木についてもありがとうございます。
確認が遅くなりすみません。拝見しました。

木の作成から視覚化、クロスバリデーションまで丁寧に説明されていて分かりやすいと感じました。
クラス分類では max_depth を設定せず木を生やせるところまで生やし、回帰では max_depth = 3 と設定するのも、違いが分かっていいですね。

一点、受講者の質問として、max_depth をどう設定したらいいの？といったような質問があるかもしれませんので、クロスバリデーションの説明のところに、max_depth を振ってスコアが高くなる値を採用することもできる、といったような文言があってもよいと思います。

ちなみに、一般的かわからないので解説に入れなくてよいと思いますが、わたしは MinSamplesLeaf を 3 とか 5 とかにして、サンプルの少ない葉ができないようにしています、FYI。

2017-10-31 23:27 UTC, yamasakih commented
>ちなみに、一般的かわからないので解説に入れなくてよいと思いますが、わたしは MinSamplesLeaf を 3 とか 5 とかにして、サンプルの少ない葉ができないようにしています、FYI。

情報ありがとうございます。
解説に入れませんが口頭で伝えたり、私自身の研究で使う時の参考にしますね。

2017-10-31 23:30 UTC, yamasakih commented
こちらでもaccuray_scoreを用いたいと思います。

2017-10-31 23:57 UTC, yamasakih commented
@hkaneko1985 san
レビューありがとうございます。

>一点、受講者の質問として、max_depth をどう設定したらいいの？といったような質問があるかもしれませんので、クロスバリデーションの説明のところに、max_depth を振ってスコアが高くなる値を採用することもできる、といったような文言があってもよいと思います。

おっしゃるとおりですね 👏 

`max_depth`を振ったスクリプトを追加してみました。
ご確認下さい。

gistはこちらです。
[DecisionTree](https://gist.github.com/yamasakih/1b661ae29b32240afdfb0f709b9e0a03)

2017-11-01 21:20 UTC, hkaneko1985 commented
修正ありがとうございます！
max_depth をふったスクリプトまで追加されて、やり方が分からない受講者もいなくなり素晴らしいです。
結果も分かりやすいです。

異論ございません！

2017-11-01 21:29 UTC, yamasakih commented
@hkaneko1985 san

kubor san のレビューが終わりました。マージしてもらいます。

レビューありがとうございました！ ☕️

2017-11-02 04:41 UTC, kubor requested changes
いいと思います！
幾つかコメントしましたのでご確認ください。

2017-11-02 04:41 UTC, kubor commented on advanced/DecisionTree.ipynb
> +    "Decision Treeのノードを視覚化するには`graphviz`という名前のソフトがインストールされている必要がある。  \n",
少し冗長な表現に聞こえるので、「Scikit-learnのDecusion Treeを用いてノードを視覚化するには `graphviz` を使用する。」という文章で良さそうです。

[Graphviz | Graphviz - Graph Visualization Software](http://www.graphviz.org/)

あとリンク加えてあげると良さげ！

2017-11-02 04:41 UTC, kubor commented on advanced/DecisionTree.ipynb
> +    "インストールされている場合以下のように実行する。"
※ `chemowakate/tutorial-7th` のDockerイメージを使用している場合はGraphvizをインストール済み

インストールされているのかどうかわかりにくい表現に感じたので、上記のように置き換えるのはいかがでしょうか。

2017-11-02 04:41 UTC, kubor commented on advanced/DecisionTree.ipynb
> +    "出力されたものをコピーし[Webgraphviz](http://www.webgraphviz.com/)にペーストしGenerate Graphをクリックすると以下のような図が表示される。"
これ、Gistだと図が表示されないですね。 jupyterだと表示されました。

2017-11-02 04:41 UTC, kubor commented on advanced/DecisionTree.ipynb
> +    "`graphviz`がインストールされていない場合はdot_dataを文字情報として出力し、  \n",
”dot_dataを文字情報として出力し、” -> ”DOTフォーマットデータをテキスト出力し、”

些細ですがDOTフォーマットというフォーマットなんだと伝える意味を込めて。

2017-11-02 04:41 UTC, kubor commented on advanced/DecisionTree.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAAA5sAAALhCAYAAADRpbADAAAgAElEQVR4AezdCVhUVf8H8O8o6OA6mOZgmWlqipaC71uJLQqaCZoCZipoKqiZWi6QJpiVSC6QlliZoGVCmYqWirZAWYlZCbiBrxsuKWgmo5IMOnDf59xZgGHYFxG+93mIu5z1
```
import matplotlib
from matplotlib import pyplot as plt

%matplotlib inline

accuracy_scores = []

for max_depth in range(1, 6):
    clf = DecisionTreeClassifier(random_state=None, max_depth=max_depth)
    score = cross_val_score(clf, X_iris, y_iris, cv=10)
    accuracy_scores.append(score)
    print(f'max_depth={max_depth}, score={score.mean()}')


X = list(range(1, 6))
plt.plot(X, accuracy_scores)

plt.xlabel('max depth')
plt.ylabel('accuracy rate')
plt.show()
```

<img width="495" alt="2017-11-02 13 28 27" src="https://user-images.githubusercontent.com/7918702/32310097-54bbe88a-bfd3-11e7-868a-c4cd14437da6.png">

こんな感じでグラフ描くTipsも示せるとよいかも

2017-11-02 04:51 UTC, yamasakih commented on advanced/DecisionTree.ipynb
> +    "Decision Treeのノードを視覚化するには`graphviz`という名前のソフトがインストールされている必要がある。  \n",
done.

2017-11-02 04:53 UTC, yamasakih commented on advanced/DecisionTree.ipynb
> +    "インストールされている場合以下のように実行する。"
done.

2017-11-02 04:54 UTC, yamasakih commented on advanced/DecisionTree.ipynb
> +    "`graphviz`がインストールされていない場合はdot_dataを文字情報として出力し、  \n",
done.

2017-11-02 04:55 UTC, yamasakih commented on advanced/DecisionTree.ipynb
> +    "出力されたものをコピーし[Webgraphviz](http://www.webgraphviz.com/)にペーストしGenerate Graphをクリックすると以下のような図が表示される。"
ほんとですね。ファイルの名前だけありますね。
今気づきました。失礼しました。

2017-11-02 05:00 UTC, yamasakih commented on advanced/DecisionTree.ipynb
> +     "image/png": "iVBORw0KGgoAAAANSUhEUgAAA5sAAALhCAYAAADRpbADAAAgAElEQVR4AezdCVhUVf8H8O8o6OA6mOZgmWlqipaC71uJLQqaCZoCZipoKqiZWi6QJpiVSC6QlliZoGVCmYqWirZAWYlZCbiBrxsuKWgmo5IMOnDf59xZgGHYFxG+93mIu5z1
LGTM ✨ 

追加してみました。

2017-11-02 05:08 UTC, yamasakih commented
@kubor san
レビューありがとうございました！ 🌮 
Fixしたのでご確認ください。

[DecisionTree.ipynb](https://gist.github.com/yamasakih/1b661ae29b32240afdfb0f709b9e0a03)

2017-11-04 00:57 UTC, hkaneko1985 approved these changes

2017-11-04 02:50 UTC, kubor approved these changes
LGTM

2017-11-04 02:50 UTC, kubor commented on advanced/DecisionTree.ipynb
> +    "from matplotlib import pyplot as plt\n",
`as plt` って謎慣習ですよね。
そんなに短くなってないし。

2017-11-04 02:50 UTC, merged

2017-11-04 03:42 UTC, yamasakih commented on advanced/DecisionTree.ipynb
> +    "from matplotlib import pyplot as plt\n",
ですよねｗ最初にはじめた人はだれだっ！