[WIP] Add RandomForest Example
chemo-wakate/tutorial-7th pull request #5
Opened 2017-10-30 08:32 UTC by yamasakih

RandomForestのドキュメントをJupyter Notebookで作成します。

2017-10-30 13:19 UTC, yamasakih commented
参考
[RandomForestClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier)
[RandomForestRegressor](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html#sklearn.ensemble.RandomForestRegressor)

2017-10-31 00:42 UTC, yamasakih commented
@kubor @hkaneko1985 
RandomForestのドキュメント完成しました。
レビューをお願いします 🐧 

gistはこちらです。
[RandomForest.ipynb](https://gist.github.com/yamasakih/15a6457e87502ea2542421887120de24)

2017-10-31 14:05 UTC, kubor requested changes
細かなところコメントしました。
大まかにはこれでいいともうのですが、RF自体の解説が口頭でいいのであれば理解度が高まるかなーという感触です。

2017-10-31 14:05 UTC, kubor commented on advanced/RandomForest.ipynb
> +    "今回は`サンプル数=100`, `説明変数の数=10`, `クラス数=2` そして再現性を担保するために`random_state=0`, `shuffle=False`とした。"
`n_samples=1000` と一致していないです。

2017-10-31 14:05 UTC, kubor commented on advanced/RandomForest.ipynb
> +    "今回は`サンプル数=100`, `説明変数の数=10`, そして再現性を担保するために`random_state=0`, `shuffle=False`とした。"
同じくサンプル数がコードと一致していないです

2017-10-31 14:05 UTC, kubor commented on advanced/RandomForest.ipynb
> +    "正答率は約8386.7であった。今回のデータセットでは決定木をより複雑にできるようにすることで大幅にRMSEが小さくなった。"
正答率 -> RMSE

2017-10-31 14:40 UTC, yamasakih commented on advanced/RandomForest.ipynb
> +    "今回は`サンプル数=100`, `説明変数の数=10`, `クラス数=2` そして再現性を担保するために`random_state=0`, `shuffle=False`とした。"
イージーミス申し訳ないです。done.

2017-10-31 14:40 UTC, yamasakih commented on advanced/RandomForest.ipynb
> +    "今回は`サンプル数=100`, `説明変数の数=10`, そして再現性を担保するために`random_state=0`, `shuffle=False`とした。"
done.

2017-10-31 14:41 UTC, yamasakih commented on advanced/RandomForest.ipynb
> +    "正答率は約8386.7であった。今回のデータセットでは決定木をより複雑にできるようにすることで大幅にRMSEが小さくなった。"
同じくイージーミスですね。ありがとうございます 👏  done.

2017-10-31 14:42 UTC, yamasakih commented
>細かなところコメントしました。
>大まかにはこれでいいともうのですが、RF自体の解説が口頭でいいのであれば理解度が高まるかなーという感触です。

一応、金子さんのRFに対する講義があるし、これは本来困ったヒトにだけみせる＆ファシリテーターが先に見ておく資料ですが、  
おっしゃることもわかりますので簡単に最初に説明文いれてみました。
ご確認ください。

2017-10-31 14:53 UTC, yamasakih commented
@kubor san 
訂正しました！ご確認ください。
いつもありがとうございます！ 🐧 

[RandomForest.ipynb](https://gist.github.com/yamasakih/15a6457e87502ea2542421887120de24)

2017-10-31 21:29 UTC, hkaneko1985 commented
山﨑さんランダムフォレストもありがとうございます。
拝見しました。

モデルの作成から予測まで分かり、とても良い資料と思います。
max_depthを2から3に増やすことで精度が向上することを示し、説明資料として全く問題ないと思いますが、max_depthをどう設定したらよいの？といった質問には、設定しなくてよい、といった回答でもよいと思います。ランダムフォレストの決定木は弱学習器でよいので、一つ一つの木を生やせるだけ生やしてオーバーフィッティングしてしまっても問題ないためです。

むしろ、max_features で一つ一つの決定木に使う説明変数の数を制御できるのですが、これを振ってクロスバリデーションで最適化することは行っています。

また、正解率の計算のところでサンプル数 "1000" を用いていますが、当日の説明でサンプル数を変えて実行してみたときように、X_clf.shape[0] としておくのが良いかと思いました。

以上です。
ランダムフォレストの解説もがんばります！

2017-10-31 21:39 UTC, yamasakih commented
@hkaneko1985 san 
レビューありがとうございます。的確な解説で助かります。

先に確認しておくと

>また、正解率の計算のところでサンプル数 "1000" を用いていますが、当日の説明でサンプル数を変えて実行してみたときように、X_clf.shape[0] としておくのが良いかと思いました。

これはおそらくサンプルサイズを変えると自動で割り算の分母が変わるようにしたいということですかね？

mean_squared_errorと同様に正答率を計算する[accuracy_score](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html#sklearn.metrics.accuracy_score)という関数を見つけたので
こちらに変えちゃおうと思います。いかがでしょうか？

scikit_learnはこの手の関数が行き届いていて助かりますね。

2017-10-31 21:49 UTC, hkaneko1985 commented
はい、おっしゃる通りです。
accuracy_scoreいいと思います！

2017-10-31 21:51 UTC, yamasakih commented
![image](https://user-images.githubusercontent.com/10294378/32250738-04c764b0-bed1-11e7-9413-a4dfb26838d2.png)

2017-10-31 21:54 UTC, hkaneko1985 commented
あと confusion_matrix も使っています。便利ですよね。

2017-10-31 22:23 UTC, yamasakih commented
ほんとだ！ありました。
[confusion_matrix](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html)

scikit-learn開発者に足向けて寝れないですね。

結構ガチで金子さんの論文に書いてた新手法もscikit-learnに導入したいですね。

2017-10-31 22:24 UTC, yamasakih commented
余談ですが、scikit-learnのリポジトリありました。
[https://github.com/scikit-learn/scikit-learn](https://github.com/scikit-learn/scikit-learn)

2017-10-31 23:20 UTC, yamasakih commented on advanced/RandomForest.ipynb
> +    "accuracy_score(y_predicted, y_clf) * 100"
accuracy_scoreに変更

2017-10-31 23:20 UTC, yamasakih commented on advanced/RandomForest.ipynb
> +   ]
max_featuresを変更したらどう正答率が変化するか調べるコードを追記

2017-10-31 23:21 UTC, yamasakih commented on advanced/RandomForest.ipynb
>     ]
金子さんのCVをするべきというコメントを考慮した文章を追記

2017-10-31 23:21 UTC, yamasakih commented on advanced/RandomForest.ipynb
> +   ]
金子さんのコメントを考慮して追記

2017-10-31 23:25 UTC, yamasakih commented
@hkaneko1985 @kubor 
金子さんのコメントを反映してリファインしました。ご確認下さい。
`max_features`を変化させたらどうなるかの例も追記しました。
減らしたら良くなる例と増やしたら良くなる例が提示できていい感じだと思います。

gistはこちらです。
[RandomForest.ipynb](https://gist.github.com/yamasakih/15a6457e87502ea2542421887120de24)

2017-11-01 09:39 UTC, kubor reviewed
いいと思います。シード値固定するかどうかだけ検討頂ければと。

2017-11-01 09:39 UTC, kubor commented on advanced/RandomForest.ipynb
> +    "RMSEは約8386.7であった。今回のデータセットでは決定木をより複雑にできるようにすることで大幅にRMSEが小さくなった。"
出力されている数値と違っているのは乱数固定してないからですか？
一旦資料としては固定したほうがわかりやすいかもですね。

どうでしょうか。

2017-11-01 09:58 UTC, yamasakih commented on advanced/RandomForest.ipynb
> +    "RMSEは約8386.7であった。今回のデータセットでは決定木をより複雑にできるようにすることで大幅にRMSEが小さくなった。"
固定しますね。

2017-11-01 09:58 UTC, yamasakih commented on advanced/RandomForest.ipynb
> +    "RMSEは約8386.7であった。今回のデータセットでは決定木をより複雑にできるようにすることで大幅にRMSEが小さくなった。"
レビューありがとうございました！✨

2017-11-01 12:47 UTC, yamasakih commented on advanced/RandomForest.ipynb
> +    "RMSEは約8386.7であった。今回のデータセットでは決定木をより複雑にできるようにすることで大幅にRMSEが小さくなった。"
`random_state=0`で固定してたのに値を変えてないだけですね。

2017-11-01 12:49 UTC, yamasakih commented
@kubor san
値を訂正しました。

2017-11-01 21:12 UTC, hkaneko1985 commented on advanced/RandomForest.ipynb
>     ]
690の文章
> 用いる説明変数の数が多すぎると分類器に差がなくなることもあり単純に増やせばよいというわけではない。

は、

用いる説明変数の数が少なすぎると分類器に差がなくなることもあり単純に減らせばよいというわけではない。

でしょうか？

2017-11-01 21:15 UTC, hkaneko1985 commented on advanced/RandomForest.ipynb
> +   ]
1324の文章
> 今回の例では用いる説明変数の数を増やすことで正答率があがった。

は、

今回の例では用いる説明変数の数を増やすことでMSEが下がった。

ということでしょうか。

2017-11-01 21:15 UTC, hkaneko1985 commented
山﨑さんコメントを反映していただきありがとうございます。
レビュー致しました。

コメントした以外は異論ございません！

2017-11-01 21:17 UTC, hkaneko1985 commented
scikit-learnのリポジトリの情報もありがとうございます！
多くの人たちの貢献で便利になっているのですね。ありがたいことです。

2017-11-01 21:32 UTC, yamasakih commented on advanced/RandomForest.ipynb
>     ]
極端な話10個の説明変数の数から9個選ぶようにしてしまうと
<sub>10</sub>C<sub>9</sub>10パターンしかなくなり分類器に差がなくなってしまうよ、という意味ですね。

少ない方については言及してませんがしますか？
それとも多い方についても不適切な表現ですかね？

2017-11-01 21:33 UTC, yamasakih commented on advanced/RandomForest.ipynb
> +   ]
そうですね！こちらは単純にミスですね。MSEに変更しておきます。
ご指摘ありがとうございます 👏

2017-11-01 21:38 UTC, yamasakih commented on advanced/RandomForest.ipynb
> +   ]
というか他のMSEと書くべきところRMSEと書いてますね。
MSEに統一しておきます。

2017-11-01 21:42 UTC, hkaneko1985 commented on advanced/RandomForest.ipynb
>     ]
どうもありがとうございます。
説明変数が多すぎるときの問題については異論ありません。

ただ、ここでは前文の
今回の例では用いる説明変数の数を"少なくすることで"正答率があがった。
を受けての文章と思いましたので、単純に少なくすればいいってもんじゃないよ、ってことで、

用いる説明変数の数が"少なすぎると"分類器に差がなくなることもあり単純に減らせばよいというわけではない。

ということを述べたかったのかな、と思いました。

2017-11-01 22:53 UTC, yamasakih commented
金子さんのコメントをもとに修正しました。
- RMSEをMSEに変更
- MSEと書くべきところを正答率と書いていたのを訂正

ご確認ください。
Gistはこちら
[RandomForest.ipynb](https://gist.github.com/yamasakih/15a6457e87502ea2542421887120de24)

2017-11-02 00:15 UTC, kubor approved these changes
LGTM

2017-11-02 00:15 UTC, merged

2017-11-02 00:35 UTC, yamasakih commented
@kubor san
まだ議論終わってないっすｗ

2017-11-02 00:40 UTC, kubor commented
んん。変更箇所確認しましたよー。

2017-11-02 00:42 UTC, yamasakih commented on advanced/RandomForest.ipynb
>     ]
@hkaneko1985 

あれ、一回書いたのに書かれてない。`Comment`ボタン押すの忘れてたのかな。
もう一度書きます。

ここの文章わかりにくくてすいません。

この文章の前で説明変数の数を減らしたモデルと増やしたモデルを作成しました。
各モデルを比較すると(ほとんど誤差の範囲だけど)減らしたモデルのほうが良くなってました。

そこで(初学者は説明変数の数を増やせばよいと誤解しそうなことだけど)説明変数の数が多すぎると分類器に差がなくなることもあり単純に増やせばよいというわけではない。

と書いてみました。

いかがでしょうか？